Repository DO-SOPT-APP6-NAVER-MAP/NAVER-MAP-AOS, pull requests merged in 2023-11, with the labels that each got.

#2 [add] 기초세팅 / color, typography 시스템 세팅
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/font/naver_map_pretendard_bold.xml
  app/src/main/res/font/naver_map_pretendard_medium.xml
  app/src/main/res/font/naver_map_pretendard_regular.xml
  app/src/main/res/font/naver_map_pretendard_semi_bold.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semi_bold.otf
  app/src/main/res/values/colors.xml
  app/src/main/res/values/typography.xml
Labels: add ➕

#6 Feature/UI main view
  app/src/main/res/drawable/ic_main_arrow_left_gray.xml
  app/src/main/res/drawable/ic_main_remove_gray.xml
  app/src/main/res/drawable/ic_main_search_gray.xml
  app/src/main/res/drawable/img_main_activity_frame.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: ui 🎨, 지현

#8 Feature/feat route view
  app/src/main/java/org/sopt/navermap/data/model/remote/request/RequestRouteImg.kt
  app/src/main/java/org/sopt/navermap/data/repository/DummyRepository.kt
  app/src/main/java/org/sopt/navermap/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/navermap/presentation/route/RouteActivity.kt
  app/src/main/java/org/sopt/navermap/presentation/route/RouteAdapter.kt
  app/src/main/java/org/sopt/navermap/util/view/viewExt.kt
  app/src/main/res/drawable/background_rec_gray.xml
  app/src/main/res/drawable/ic_bike_black_24.xml
  app/src/main/res/drawable/ic_bustime_blue_24.xml
  app/src/main/res/drawable/ic_car_black_24.xml
  app/src/main/res/drawable/ic_change_black_24.xml
  app/src/main/res/drawable/ic_line_gray_.xml
  app/src/main/res/drawable/ic_multiply_black_24.xml
  app/src/main/res/drawable/ic_refresh_black_24.xml
  app/src/main/res/drawable/ic_star_black_24.xml
  app/src/main/res/drawable/ic_upload_white_24.xml
  app/src/main/res/drawable/ic_walk_black_24.xml
  app/src/main/res/drawable/img_dummy_rec.png
  app/src/main/res/drawable/tap_choice_transport.xml
  app/src/main/res/layout/activity_route.xml
  app/src/main/res/layout/item_route.xml
  app/src/main/res/values/strings.xml
Labels: ui 🎨, feat 🖥️, 채은

#12 Feature/UI searchresult view
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/navermap/App.kt
  app/src/main/java/org/sopt/navermap/data/model/local/SearchResult.kt
  app/src/main/java/org/sopt/navermap/presentation/search/result/TestSearchActivity.kt
  app/src/main/java/org/sopt/navermap/presentation/search/result/TestSearchViewModel.kt
  app/src/main/res/layout/activity_test_search.xml
  settings.gradle
Labels: ui 🎨, 민정

#13 Feature/UI detail view
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/navermap/presentation/detail/DetailActivity.kt
  app/src/main/res/drawable/ic_detail_arrive.xml
  app/src/main/res/drawable/ic_detail_arrowdown.xml
  app/src/main/res/drawable/ic_detail_arrowright.xml
  app/src/main/res/drawable/ic_detail_arrowup_btn.xml
  app/src/main/res/drawable/ic_detail_back.xml
  app/src/main/res/drawable/ic_detail_calendar.xml
  app/src/main/res/drawable/ic_detail_call.xml
  app/src/main/res/drawable/ic_detail_close.xml
  app/src/main/res/drawable/ic_detail_depart.xml
  app/src/main/res/drawable/ic_detail_dot.xml
  app/src/main/res/drawable/ic_detail_footer.xml
  app/src/main/res/drawable/ic_detail_home.xml
  app/src/main/res/drawable/ic_detail_info.xml
  app/src/main/res/drawable/ic_detail_internet.xml
  app/src/main/res/drawable/ic_detail_location.xml
  app/src/main/res/drawable/ic_detail_metro7.xml
  app/src/main/res/drawable/ic_detail_navigation.xml
  app/src/main/res/drawable/ic_detail_noti.xml
  app/src/main/res/drawable/ic_detail_phone.xml
  app/src/main/res/drawable/ic_detail_profile.xml
  app/src/main/res/drawable/ic_detail_save.xml
  app/src/main/res/drawable/ic_detail_share.xml
  app/src/main/res/drawable/ic_detail_star.xml
  app/src/main/res/drawable/ic_detail_time.xml
  app/src/main/res/drawable/ic_detail_write.xml
  app/src/main/res/drawable/img_detail_diningcord.png
  app/src/main/res/drawable/img_detail_menu1.png
  app/src/main/res/drawable/img_detail_menu2.png
  app/src/main/res/drawable/img_detail_menu3.png
  app/src/main/res/drawable/img_detail_menu4.png
  app/src/main/res/drawable/sel_detail_tablayout.xml
  app/src/main/res/drawable/shape_black_line.xml
  app/src/main/res/drawable/shape_gray_fill_20_rectangle.xml
  app/src/main/res/drawable/shape_gray_fill_6_rectangle.xml
  app/src/main/res/drawable/shape_gray_line_8_rectangle.xml
  app/src/main/res/drawable/shape_green_fill_3_rectangle.xml
  app/src/main/res/drawable/shape_green_fill_6_rectangle.xml
  app/src/main/res/drawable/shape_white_fill_round.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/values/themes.xml
  settings.gradle
Labels: ui 🎨

#19 Feature/feat Route serve
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/navermap/data/ApiFactory.kt
  app/src/main/java/org/sopt/navermap/data/model/remote/request/RequestData.kt
  app/src/main/java/org/sopt/navermap/data/model/remote/request/RequestRouteImg.kt
  app/src/main/java/org/sopt/navermap/data/model/remote/response/ResponseGetPlaceDto.kt
  app/src/main/java/org/sopt/navermap/data/repository/RouteRepository.kt
  app/src/main/java/org/sopt/navermap/data/service/RouteService.kt
  app/src/main/java/org/sopt/navermap/presentation/route/RouteActivity.kt
  app/src/main/java/org/sopt/navermap/presentation/route/RouteAdapter.kt
  app/src/main/java/org/sopt/navermap/presentation/route/RouteViewHolder.kt
  app/src/main/java/org/sopt/navermap/presentation/route/RouteViewModel.kt
  app/src/main/java/org/sopt/navermap/presentation/route/RouteViewModelFactory.kt
  app/src/main/res/layout/activity_route.xml
  app/src/main/res/layout/item_route.xml
  app/src/main/res/values/strings.xml
Labels: feat 🖥️, 채은
